project_id = "nzqbbpzxrdusqtolrwco"

[functions.analyze-proposal]
verify_jwt = true

[functions.lead-analyst]
verify_jwt = true

[functions.send-goal-reminder]
verify_jwt = true

[functions.moneybird-connect]
verify_jwt = true