// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzqbbpzxrdusqtolrwco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cWJicHp4cmR1c3F0b2xyd2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjExMDgsImV4cCI6MjA2OTI5NzEwOH0.EJZx-u1IrN9RFbuoSuVRbUkIvlXQiCZ1pRsy2r5Ef3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});